config/routes.rb
Rails.application.routes.draw do
  root to: 'wines#index'

  resources :wines, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wine.rb
class Wine < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]

  # GET /wines
  # GET /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1
  # GET /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines
  # POST /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: 'Wine was successfully created.' }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1
  # PATCH/PUT /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: 'Wine was successfully updated.' }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1
  # DELETE /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Wine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, :winery, :rating, :region, :grapes, :color, :wine_style, :food_pairing, :year, :story, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vinity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wines/_form.html.erb
<%= simple_form_for(@wine) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :winery %>
    <%= f.input :rating %>
    <%= f.input :region %>
    <%= f.input :grapes %>
    <%= f.input :color %>
    <%= f.input :wine_style %>
    <%= f.input :food_pairing %>
    <%= f.input :year %>
    <%= f.input :story %>
    <%= f.input :price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', root_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Winery</th>
      <th>Rating</th>
      <th>Region</th>
      <th>Grapes</th>
      <th>Color</th>
      <th>Wine style</th>
      <th>Food pairing</th>
      <th>Year</th>
      <th>Story</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.winery %></td>
        <td><%= wine.rating %></td>
        <td><%= wine.region %></td>
        <td><%= wine.grapes %></td>
        <td><%= wine.color %></td>
        <td><%= wine.wine_style %></td>
        <td><%= wine.food_pairing %></td>
        <td><%= wine.year %></td>
        <td><%= wine.story %></td>
        <td><%= wine.price %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', root_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<p>
  <strong>Winery:</strong>
  <%= @wine.winery %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @wine.rating %>
</p>

<p>
  <strong>Region:</strong>
  <%= @wine.region %>
</p>

<p>
  <strong>Grapes:</strong>
  <%= @wine.grapes %>
</p>

<p>
  <strong>Color:</strong>
  <%= @wine.color %>
</p>

<p>
  <strong>Wine style:</strong>
  <%= @wine.wine_style %>
</p>

<p>
  <strong>Food pairing:</strong>
  <%= @wine.food_pairing %>
</p>

<p>
  <strong>Year:</strong>
  <%= @wine.year %>
</p>

<p>
  <strong>Story:</strong>
  <%= @wine.story %>
</p>

<p>
  <strong>Price:</strong>
  <%= @wine.price %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', root_path %>